Criação classes bases
willsantos/pomoday_api pull request #11
Opened 2023-04-25 19:37 UTC by Edileal

fix #2 
Criação das classes bases:
BaseEntity;
BaseRepository;
BaseService;

Criação das classes ClaimUtil, ConstanteUtil e TextUtil.

2023-04-25 19:44 UTC, willsantos requested changes
Me explica aí nos comentários de cada observação.

2023-04-25 19:44 UTC, willsantos commented on Pomoday.Domain/Utils/ConstanteUtil.cs
De onde vc tirou esse perfil colaborador e administrador que não tem no escopo?

2023-04-25 19:44 UTC, willsantos commented on Pomoday.Domain/Utils/TextUtil.cs
Pra que isso?

2023-04-25 19:44 UTC, willsantos commented on Pomoday.Repository/Repositories/BaseRepository.cs
Ué, e esses NotImplementedException ?

2023-04-25 19:54 UTC, Edileal commented on Pomoday.Domain/Utils/ConstanteUtil.cs
Achei que teria. Vou retirar. KKKKK não deixe esse projeto público jamais.

2023-04-25 19:56 UTC, Edileal commented on Pomoday.Repository/Repositories/BaseRepository.cs
Vou implementar no próximo commit.

2023-04-25 19:57 UTC, Edileal commented on Pomoday.Domain/Utils/TextUtil.cs
Como não haverá sistema de usuário administrador/colaborador, irei remover.

2023-04-26 17:39 UTC, willsantos approved these changes
Agora ficou bonito

2023-04-26 17:39 UTC, merged