Feat/criar entity usuarios
willsantos/pomoday_api pull request #12
Opened 2023-04-26 20:26 UTC by Edileal

fix #3
fix #4 
fix #5 

Base service por enquanto ficará comentada, pois iremos avaliar a sua viabilidade neste projeto;
Acréscimo de retornos nos métodos do CRUD;
Criação dos UsuarioRequest e UsuarioResponse;

2023-04-26 20:52 UTC, willsantos requested changes
Mais perguntinhas

2023-04-26 20:52 UTC, willsantos commented on Pomoday.Domain/Contracts/Requests/UsuarioRequest.cs
> +        [StringLength(18, MinimumLength = 6)]
não se limita tamanho de senha, dá uma olhada se tem como deixar sem limite senão tiver coloca 99

2023-04-26 20:52 UTC, willsantos commented on Pomoday.Service/Services/BaseService.cs
Porque esse código todo comentado?

2023-04-26 20:52 UTC, willsantos commented on Pomoday.Service/Services/UsuarioService.cs
> +            throw new NotImplementedException();
Not Implemented?

2023-04-27 18:39 UTC, Edileal commented on Pomoday.Domain/Contracts/Requests/UsuarioRequest.cs
> +        [StringLength(18, MinimumLength = 6)]
ok.

2023-04-27 18:39 UTC, Edileal commented on Pomoday.Service/Services/BaseService.cs
Se no futuro for utilizar, estará lá. Caso contrário, apagaremos.

2023-04-27 19:03 UTC, Edileal commented on Pomoday.Service/Services/UsuarioService.cs
> +            throw new NotImplementedException();
Corrigido.

2023-04-28 10:52 UTC, willsantos approved these changes
Correções aprovadas.

2023-04-28 10:52 UTC, merged