Feat/criar controller usuarios
willsantos/pomoday_api pull request #17
Opened 2023-05-02 14:03 UTC by Edileal

fix #6 
fix #8

2023-05-02 16:46 UTC, willsantos requested changes
A estrutura está ok, algumas modificações importantes.

2023-05-02 16:46 UTC, willsantos commented on Pomoday.Api/Controllers/UsuarioController.cs
> +        /// <response code="201">Retorna usuário cadastrado</response>
Vou comentar só aqui, mas isso se repete em todas as endpoints abaixo.

Na doc do swagger vc diz que pode retornar tanto um 201 quanto um 400

Porém a unica possibilidade do seu código é retornar um 200

2023-05-02 16:46 UTC, willsantos commented on Pomoday.CrossCutting/Pomoday.CrossCutting.csproj
> +    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.22" />
Vc tá usando o Pomello ou o da Microsoft?

Acho que é melhor optar pelo Pomello.

2023-05-02 16:46 UTC, willsantos commented on Pomoday.Api/appsettings.Development.json
> +    "Pomoday.Api": "server=localhost;port=3306;database=mydatabase;user=root;password=mypassword"
Vc entrou na issue para ver os detalhes? não vamos usar o json para guardar dados sensiveis.

2023-05-02 16:47 UTC, Edileal commented on Pomoday.CrossCutting/Pomoday.CrossCutting.csproj
> +    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.22" />
Pomello.

2023-05-03 19:06 UTC, willsantos approved these changes
Boa

2023-05-03 19:06 UTC, merged